
development:
  adapter: postgresql
  encoding: unicode
  database: rockr_development
  host: localhost
  pool: 5
  username: ronjones
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: rockr_test
  host: localhost
  pool: 5
  username: ronjones
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rockr_production
  host: localhost
  pool: 5
  username: ronjones
  password:
